baseURL = "https://determined-mclean-eafee0.netlify.com/"
languageCode = "es"
title = "Juan Cruz Santos | Psicologo"
theme = "AllinOne"

## Language
DefaultContentLanguage     = "es"
[languages]
  [languages.es]
    languageName = "Spanish"
    weight = 1


## Custom
builddrafts                = false
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

## 

[permalinks]
  blog                     = "blog/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Inicio"
    weight                 = -130
    identifier             = "home"
    url                    = "/"  

  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  


  [[menu.main]]
    name                   = "Quien soy?"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = ""               # from static/
  avatar                   = "img/profile.jpeg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Juan Cruz Santos"
  description              = ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ratione molestiae laboriosam accusantium laudantium repellat quia perferendis est sint, pariatur consequuntur, repellendus culpa quae itaque voluptate qui explicabo quaerat maxime laborum."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Bienvenidx a mi blog!"
  welcome_word             = "alguna frase"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "contact@juancruzsantos.com.ar"
  linkedin                 = "//linkedin.com/in/juancruzsantos"
  facebook                 = "//facebook.com/juancruzsantos"
  twitter                  = "//twitter.com/juancruzsantos" 
  instagram                = "//instagram.com/juancruzsantos"
  #include_rss                   # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"